# Generated by Django 3.2.3 on 2021-05-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_number', models.IntegerField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=64, verbose_name='название игры')),
                ('Game_go', models.BooleanField(default=False)),
                ('now_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название уровня')),
                ('task', models.TextField(verbose_name='текст задания')),
                ('image', models.ImageField(blank=True, upload_to='level_img')),
                ('level_active', models.BooleanField(default=False)),
                ('level_done', models.BooleanField(default=False)),
                ('level_last', models.BooleanField(default=False)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('level_of_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.game', verbose_name='игра')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.gamelevel', verbose_name='уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Promt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promt', models.CharField(blank=True, max_length=256, verbose_name='подсказка')),
                ('image', models.ImageField(blank=True, upload_to='promt_img')),
                ('counter', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.gamelevel', verbose_name='уровень')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.gamelevel', verbose_name='уровень')),
            ],
        ),
    ]
