# Generated by Django 3.2.3 on 2021-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, blank=True),
            preserve_default=False,
        ),
    ]
