# Generated by Django 3.2.3 on 2021-05-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='now_level',
        ),
    ]
