# Generated by Django 3.2.3 on 2021-05-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_remove_game_now_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='now_level',
            field=models.IntegerField(default=1),
        ),
    ]
